<?php

namespace Database\Seeders;

use App\Models\Place;
use Illuminate\Database\Seeder;

class PlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $places = [
            [
                'name' => 'Toko Kue Semprong',
                'description' => 'Restoran kuliner tradisional Pontianak terkenal dengan hidangan semprong dan masakan Melayu autentik. Tempat ini menjadi destinasi utama untuk mencicipi cita rasa tradisional Pontianak.',
                'longitude' => 109.3356,
                'latitude' => -0.0259,
                'image_urls' => json_encode(['https://example.com/semprong1.jpg', 'https://example.com/semprong2.jpg']),
                'coin_reward' => 50,
                'exp_reward' => 100,
                'min_price' => 25000,
                'max_price' => 150000,
                'avg_rating' => 4.6,
                'total_review' => 145,
                'total_checkin' => 523,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 750-123', 'type' => 'Traditional Food'])
            ],
            [
                'name' => 'Nasi Kuning Pontianak',
                'description' => 'Rumah makan khusus nasi kuning dengan resep turun temurun keluarga. Menyajikan nasi kuning premium dengan lauk pauk pilihan seperti ayam goreng dan ikan bakar.',
                'longitude' => 109.3421,
                'latitude' => -0.0315,
                'image_urls' => json_encode(['https://example.com/nasikuning1.jpg', 'https://example.com/nasikuning2.jpg']),
                'coin_reward' => 40,
                'exp_reward' => 80,
                'min_price' => 20000,
                'max_price' => 80000,
                'avg_rating' => 4.5,
                'total_review' => 198,
                'total_checkin' => 687,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 823-456', 'type' => 'Rice Dish'])
            ],
            [
                'name' => 'Bakso Mak Utuh',
                'description' => 'Warung bakso legendaris di Pontianak sejak tahun 1985. Dikenal dengan bakso premium dengan kuah tradisional yang gurih dan daging berkualitas tinggi. Selalu ramai pada jam makan siang dan malam.',
                'longitude' => 109.3289,
                'latitude' => -0.0156,
                'image_urls' => json_encode(['https://example.com/bakso1.jpg', 'https://example.com/bakso2.jpg']),
                'coin_reward' => 45,
                'exp_reward' => 90,
                'min_price' => 15000,
                'max_price' => 60000,
                'avg_rating' => 4.7,
                'total_review' => 287,
                'total_checkin' => 912,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 712-789', 'type' => 'Soup/Broth'])
            ],
            [
                'name' => 'Soto Ayam Pontianak',
                'description' => 'Rumah makan spesialis soto ayam dengan resep warisan yang kaya akan rempah dan aromatis. Cocok untuk sarapan pagi atau makan siang dengan menu lengkap dan harga terjangkau.',
                'longitude' => 109.3512,
                'latitude' => -0.0421,
                'image_urls' => json_encode(['https://example.com/soto1.jpg', 'https://example.com/soto2.jpg']),
                'coin_reward' => 35,
                'exp_reward' => 70,
                'min_price' => 18000,
                'max_price' => 65000,
                'avg_rating' => 4.4,
                'total_review' => 156,
                'total_checkin' => 534,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 845-234', 'type' => 'Soup'])
            ],
            [
                'name' => 'Ikan Bakar Tepi Sungai',
                'description' => 'Restoran ikan bakar dengan lokasi strategis di tepi Sungai Kapuas. Menyajikan berbagai jenis ikan bakar segar dengan bumbu khas Pontianak. Ambiance yang nyaman dengan pemandangan sungai yang indah.',
                'longitude' => 109.3178,
                'latitude' => -0.0087,
                'image_urls' => json_encode(['https://example.com/ibanbakar1.jpg', 'https://example.com/ibanbakar2.jpg']),
                'coin_reward' => 60,
                'exp_reward' => 120,
                'min_price' => 50000,
                'max_price' => 200000,
                'avg_rating' => 4.8,
                'total_review' => 412,
                'total_checkin' => 1203,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 934-567', 'type' => 'Grilled Fish', 'outdoor_seating' => true])
            ],
            [
                'name' => 'Lumpia Goreng Istimewa',
                'description' => 'Tempat yang terkenal dengan lumpia goreng tradisional Pontianak yang renyah dan berisi. Berbagai varian isi mulai dari udang, daging, hingga sayuran. Perfect untuk oleh-oleh atau cemilan.',
                'longitude' => 109.3356,
                'latitude' => -0.0259,
                'image_urls' => json_encode(['https://example.com/lumpia1.jpg', 'https://example.com/lumpia2.jpg']),
                'coin_reward' => 30,
                'exp_reward' => 60,
                'min_price' => 12000,
                'max_price' => 50000,
                'avg_rating' => 4.5,
                'total_review' => 267,
                'total_checkin' => 756,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 756-890', 'type' => 'Snack/Appetizer'])
            ],
            [
                'name' => 'Mie Lezat Pontianak',
                'description' => 'Kedai mie yang menyajikan berbagai varian mie lokal Pontianak dengan kuah yang nikmat. Bahan berkualitas dan harga yang sangat bersahabat untuk semua kalangan. Open dari pagi hingga malam.',
                'longitude' => 109.3478,
                'latitude' => -0.0287,
                'image_urls' => json_encode(['https://example.com/mie1.jpg', 'https://example.com/mie2.jpg']),
                'coin_reward' => 25,
                'exp_reward' => 50,
                'min_price' => 15000,
                'max_price' => 55000,
                'avg_rating' => 4.3,
                'total_review' => 189,
                'total_checkin' => 612,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 623-123', 'type' => 'Noodles'])
            ],
            [
                'name' => 'Ayam Goreng Rahmat',
                'description' => 'Restoran ayam goreng dengan resep rahasia yang telah dipercaya sejak puluhan tahun. Ayam goreng yang empuk dengan bumbu yang meresap sempurna. Cocok untuk keluarga dengan harga terjangkau.',
                'longitude' => 109.3345,
                'latitude' => -0.0198,
                'image_urls' => json_encode(['https://example.com/ayamgoreng1.jpg', 'https://example.com/ayamgoreng2.jpg']),
                'coin_reward' => 40,
                'exp_reward' => 80,
                'min_price' => 25000,
                'max_price' => 120000,
                'avg_rating' => 4.6,
                'total_review' => 334,
                'total_checkin' => 1045,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 534-456', 'type' => 'Fried Chicken'])
            ],
            [
                'name' => 'Kue Tradisional Bunda',
                'description' => 'Toko kue tradisional yang menjual berbagai macam kue dan pastry khas Pontianak seperti penyaram, burgo, dan martabak. Bahan premium dan proses pembuatan yang higienis.',
                'longitude' => 109.3521,
                'latitude' => -0.0356,
                'image_urls' => json_encode(['https://example.com/kue1.jpg', 'https://example.com/kue2.jpg']),
                'coin_reward' => 20,
                'exp_reward' => 40,
                'min_price' => 8000,
                'max_price' => 40000,
                'avg_rating' => 4.4,
                'total_review' => 145,
                'total_checkin' => 423,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 823-567', 'type' => 'Pastry/Dessert'])
            ],
            [
                'name' => 'Seafood Premium Pontianak',
                'description' => 'Restoran seafood mewah menyajikan berbagai pilihan hidangan laut segar dengan kualitas premium. Lokasi strategis di pusat kota dengan interior modern dan layanan profesional.',
                'longitude' => 109.3612,
                'latitude' => -0.0445,
                'image_urls' => json_encode(['https://example.com/seafood1.jpg', 'https://example.com/seafood2.jpg']),
                'coin_reward' => 75,
                'exp_reward' => 150,
                'min_price' => 80000,
                'max_price' => 300000,
                'avg_rating' => 4.7,
                'total_review' => 289,
                'total_checkin' => 834,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 945-678', 'type' => 'Seafood', 'parking' => 'available'])
            ],
            [
                'name' => 'Teh Botol Sore Pontianak',
                'description' => 'Warung teh legendaris yang menyajikan berbagai minuman segar dan snack ringan. Tempat favorit untuk bersantai sore hari dengan suasana yang santai dan ramah. Menu snack khas Pontianak lengkap.',
                'longitude' => 109.3267,
                'latitude' => -0.0321,
                'image_urls' => json_encode(['https://example.com/teh1.jpg', 'https://example.com/teh2.jpg']),
                'coin_reward' => 15,
                'exp_reward' => 30,
                'min_price' => 5000,
                'max_price' => 30000,
                'avg_rating' => 4.2,
                'total_review' => 267,
                'total_checkin' => 892,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 734-123', 'type' => 'Tea/Drinks'])
            ],
            [
                'name' => 'Resep Nenek Padang Style',
                'description' => 'Rumah makan dengan menu masakan Padang yang autentik namun dengan cita rasa yang disesuaikan untuk lidah Pontianak. Hidangan berkualitas dengan harga yang bersaing dan porsi yang besar.',
                'longitude' => 109.3389,
                'latitude' => -0.0112,
                'image_urls' => json_encode(['https://example.com/padang1.jpg', 'https://example.com/padang2.jpg']),
                'coin_reward' => 35,
                'exp_reward' => 70,
                'min_price' => 20000,
                'max_price' => 85000,
                'avg_rating' => 4.5,
                'total_review' => 198,
                'total_checkin' => 645,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 645-789', 'type' => 'Indonesian'])
            ],
            [
                'name' => 'Martabak Istimewa Corner',
                'description' => 'Kios martabak yang terkenal dengan varian rasa yang sangat beragam dari telur, daging, keju, hingga cokelat. Martabak dibuat fresh dan renyah, selalu antri pengunjung setiap harinya.',
                'longitude' => 109.3434,
                'latitude' => -0.0287,
                'image_urls' => json_encode(['https://example.com/martabak1.jpg', 'https://example.com/martabak2.jpg']),
                'coin_reward' => 25,
                'exp_reward' => 50,
                'min_price' => 12000,
                'max_price' => 45000,
                'avg_rating' => 4.6,
                'total_review' => 356,
                'total_checkin' => 1124,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 834-567', 'type' => 'Snack'])
            ],
            [
                'name' => 'Kopi Nikmat Pagi Hari',
                'description' => 'Kedai kopi modern dengan konsep malam rustic yang cozy. Menyajikan berbagai varian kopi specialty dengan barista berpengalaman. Menu breakfast lengkap mulai dari pastry hingga sandwich.',
                'longitude' => 109.3289,
                'latitude' => -0.0445,
                'image_urls' => json_encode(['https://example.com/kopi1.jpg', 'https://example.com/kopi2.jpg']),
                'coin_reward' => 30,
                'exp_reward' => 60,
                'min_price' => 20000,
                'max_price' => 75000,
                'avg_rating' => 4.5,
                'total_review' => 234,
                'total_checkin' => 723,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 756-234', 'type' => 'Cafe', 'wifi' => true])
            ],
            [
                'name' => 'Bubur Manado Sedap',
                'description' => 'Restoran yang menyajikan bubur Manado dengan resep otentik dan cita rasa yang kuat. Menu lengkap dengan berbagai lauk pendamping pilihan. Cocok untuk sarapan dengan suasana yang hangat dan meriah.',
                'longitude' => 109.3167,
                'latitude' => -0.0234,
                'image_urls' => json_encode(['https://example.com/bubur1.jpg', 'https://example.com/bubur2.jpg']),
                'coin_reward' => 28,
                'exp_reward' => 55,
                'min_price' => 18000,
                'max_price' => 70000,
                'avg_rating' => 4.3,
                'total_review' => 156,
                'total_checkin' => 501,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 923-456', 'type' => 'Porridge'])
            ],
            [
                'name' => 'Sate Khas Pontianak',
                'description' => 'Warung sate dengan menu spesial sate khas Pontianak menggunakan bumbu tradisional yang istimewa. Daging berkualitas premium yang ditusuk dan dibakar dengan sempurna. Bumbunya kental dan menggugah selera.',
                'longitude' => 109.3545,
                'latitude' => -0.0167,
                'image_urls' => json_encode(['https://example.com/sate1.jpg', 'https://example.com/sate2.jpg']),
                'coin_reward' => 50,
                'exp_reward' => 100,
                'min_price' => 35000,
                'max_price' => 150000,
                'avg_rating' => 4.7,
                'total_review' => 276,
                'total_checkin' => 876,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 834-123', 'type' => 'Skewered Meat'])
            ],
            [
                'name' => 'Pecel Lele Mas Yanto',
                'description' => 'Rumah makan pecel lele yang sudah terkenal di Pontianak dengan ikan lele goreng yang garing dan saos sambal yang pas. Menu pendamping beragam dengan nasi putih yang gurih dan terbaik.',
                'longitude' => 109.3401,
                'latitude' => -0.0398,
                'image_urls' => json_encode(['https://example.com/pecel1.jpg', 'https://example.com/pecel2.jpg']),
                'coin_reward' => 32,
                'exp_reward' => 65,
                'min_price' => 20000,
                'max_price' => 75000,
                'avg_rating' => 4.4,
                'total_review' => 198,
                'total_checkin' => 634,
                'status' => true,
                'partnership_status' => true,
                'additional_info' => json_encode(['phone' => '(0561) 645-234', 'type' => 'Fried Catfish'])
            ]
        ];

        foreach ($places as $place) {
            Place::create($place);
        }
    }
}
